name: Deploy Node.js App to ECS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        id: build
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build -t my-app:$IMAGE_TAG .

          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  push:
    runs-on: self-hosted
    needs: build
    outputs:
      image_uri: ${{ steps.push.outputs.image_uri }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag & Push
        id: push
        run: |
          IMAGE_TAG=${{ needs.build.outputs.image_tag }}
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

          docker tag my-app:$IMAGE_TAG $IMAGE_URI
          docker push $IMAGE_URI

          echo "image_uri=$IMAGE_URI" >> $GITHUB_OUTPUT

  deploy:
    runs-on: self-hosted
    needs: push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Render ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./task-definition.json
          container-name: ${{ secrets.CONTAINER_NAME }}
          image: ${{ needs.push.outputs.image_uri }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true