name: Deploy Node.js App to ECS

permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        id: build
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          docker build --no-cache -t ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG .
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

  sast:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          ram: 2048
          threads: 2

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build || echo "No build step"

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  push:
    runs-on: self-hosted
    needs: sast

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag & Push Docker image
        run: |
          IMAGE_TAG=${{ needs.build.outputs.image_tag }}
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG

          docker tag ${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG $IMAGE_URI
          docker push $IMAGE_URI

  deploy:
    runs-on: self-hosted
    needs: push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set IMAGE_URI
        run: |
          IMAGE_TAG=${{ needs.build.outputs.image_tag }}
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:$IMAGE_TAG
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

      - name: Debug image uri
        run: echo "IMAGE = $IMAGE_URI"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Render ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./task-definition.json
          container-name: ${{ secrets.CONTAINER_NAME }}
          image: ${{ env.IMAGE_URI }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true

  dast:
    runs-on: self-hosted
    needs: deploy

    steps:
      - name: Run DAST (OWASP ZAP)
        run: |
          docker run --rm owasp/zap2docker-stable zap-baseline.py \
            -t http://thanakrit.online/demo-api \
            -r zap-report.html

      - name: Upload DAST Report
        uses: actions/upload-artifact@v4
        with:
          name: dast-report
          path: zap-report.html